### ISSUE TITLE
64bit build

### ISSUE THREAD

**Issue by BurnerGR** [kaimallea/demoinfogo-linux#38] opened 2019-01-31 14:28 UTC
I'm trying to get demoinfogo on to run on linux subsystem for windows, which does not execute 32bit ELF binaries.
protobuf compiles cleanly but demoinfogo doesn't. I'm aware that this is not a bug but its still desirable update the code to compile on 64bit, so perhaps give it a shot :)

**Comment by kaimallea** [comment] 2019-02-04 03:56
Check the README. `demoinfogo` will only compile as a 32-bit binary. if you're on a 64-bit system, you need to install `g++-multilib` so that you can compile and execute it

**Comment by BurnerGR** [comment] 2019-02-04 10:26
Yes, that works on a real linux which can execute both 32 and 64 bit binaries but not on linux subsystem for windows, which can't execute 32 bit binaries, regardless of g++-multilib.
It compile fine, it just throw an error on execution.
As i said, this is not a bug, its would just be nice to have it compile without the -m32 switch.
And thank you for a great work, the linux port of demoinfogo is really useful for us, the 64bit issue is just a hurdle, not something we can't work around.

**Comment by kaimallea** [comment] 2019-02-13 23:24
I haven't dug into the codebase in a while, but compiling as a 64-bit binary (removing `-m32`) will change the way the compiler handles `long` integers; they will be 8 bytes instead of 4 bytes, breaking some of the code that depends on specific byte lengths for reading binary data. It's possible to make it work, but code would need to be modified. This applies to the demoinfogo code as well as protobuf as that is also compiled as 32-bit.

**Comment by kaimallea** [comment] 2019-02-13 23:40
Going to close this since it's not a bug. Good luck and PRs are always accepted. 😄

**Closed as completed by kaimallea** 2019-02-13 23:40 UTC
